// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:db981dca-b151-445c-8dbe-b263deb9cdf4",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_Lg35f5pYN",
    "aws_user_pools_web_client_id": "1qnho2kdgnhluhkrqeck8bk00k"
};


export default awsmobile;
